[package]
authors = ["Guillaume Gomez <guillaume1.gomez@gmail.com>"]
license = "Apache-2.0"
name = "rustdoc-stripper"
version = "0.1.0"

[[bin]]
name = "rustdoc-stripper"

[dev-dependencies]
tempdir = "0.3.4"

[lib]
crate-type = ["dylib", "rlib"]
name = "stripper_lib"
