[package]
name = "rustdoc-stripper"
version = "0.1.0"
authors = ["Guillaume Gomez <guillaume1.gomez@gmail.com>"]
license = "Apache-2.0"

[dependencies]
stripper_interface = "0.0.4"

[lib]
name = "stripper_lib"
crate-type = ["dylib", "rlib"]

[[bin]]
name = "rustdoc-stripper"
